/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwitterSummaryRouteImport } from './routes/twitter-summary'
import { Route as TwitterOnlyRouteImport } from './routes/twitter-only'
import { Route as OgpOnlyRouteImport } from './routes/ogp-only'
import { Route as OgpNoTwitterImageRouteImport } from './routes/ogp-no-twitter-image'
import { Route as BothRouteImport } from './routes/both'
import { Route as IndexRouteImport } from './routes/index'

const TwitterSummaryRoute = TwitterSummaryRouteImport.update({
  id: '/twitter-summary',
  path: '/twitter-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterOnlyRoute = TwitterOnlyRouteImport.update({
  id: '/twitter-only',
  path: '/twitter-only',
  getParentRoute: () => rootRouteImport,
} as any)
const OgpOnlyRoute = OgpOnlyRouteImport.update({
  id: '/ogp-only',
  path: '/ogp-only',
  getParentRoute: () => rootRouteImport,
} as any)
const OgpNoTwitterImageRoute = OgpNoTwitterImageRouteImport.update({
  id: '/ogp-no-twitter-image',
  path: '/ogp-no-twitter-image',
  getParentRoute: () => rootRouteImport,
} as any)
const BothRoute = BothRouteImport.update({
  id: '/both',
  path: '/both',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/both': typeof BothRoute
  '/ogp-no-twitter-image': typeof OgpNoTwitterImageRoute
  '/ogp-only': typeof OgpOnlyRoute
  '/twitter-only': typeof TwitterOnlyRoute
  '/twitter-summary': typeof TwitterSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/both': typeof BothRoute
  '/ogp-no-twitter-image': typeof OgpNoTwitterImageRoute
  '/ogp-only': typeof OgpOnlyRoute
  '/twitter-only': typeof TwitterOnlyRoute
  '/twitter-summary': typeof TwitterSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/both': typeof BothRoute
  '/ogp-no-twitter-image': typeof OgpNoTwitterImageRoute
  '/ogp-only': typeof OgpOnlyRoute
  '/twitter-only': typeof TwitterOnlyRoute
  '/twitter-summary': typeof TwitterSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/both'
    | '/ogp-no-twitter-image'
    | '/ogp-only'
    | '/twitter-only'
    | '/twitter-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/both'
    | '/ogp-no-twitter-image'
    | '/ogp-only'
    | '/twitter-only'
    | '/twitter-summary'
  id:
    | '__root__'
    | '/'
    | '/both'
    | '/ogp-no-twitter-image'
    | '/ogp-only'
    | '/twitter-only'
    | '/twitter-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BothRoute: typeof BothRoute
  OgpNoTwitterImageRoute: typeof OgpNoTwitterImageRoute
  OgpOnlyRoute: typeof OgpOnlyRoute
  TwitterOnlyRoute: typeof TwitterOnlyRoute
  TwitterSummaryRoute: typeof TwitterSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twitter-summary': {
      id: '/twitter-summary'
      path: '/twitter-summary'
      fullPath: '/twitter-summary'
      preLoaderRoute: typeof TwitterSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter-only': {
      id: '/twitter-only'
      path: '/twitter-only'
      fullPath: '/twitter-only'
      preLoaderRoute: typeof TwitterOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogp-only': {
      id: '/ogp-only'
      path: '/ogp-only'
      fullPath: '/ogp-only'
      preLoaderRoute: typeof OgpOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogp-no-twitter-image': {
      id: '/ogp-no-twitter-image'
      path: '/ogp-no-twitter-image'
      fullPath: '/ogp-no-twitter-image'
      preLoaderRoute: typeof OgpNoTwitterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/both': {
      id: '/both'
      path: '/both'
      fullPath: '/both'
      preLoaderRoute: typeof BothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BothRoute: BothRoute,
  OgpNoTwitterImageRoute: OgpNoTwitterImageRoute,
  OgpOnlyRoute: OgpOnlyRoute,
  TwitterOnlyRoute: TwitterOnlyRoute,
  TwitterSummaryRoute: TwitterSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
